### ISSUE TITLE
Global symbol "@lfq"

### ISSUE THREAD

**Issue by Eljensen** [evoeco/radtools#1]
Hello,
I am trying to use preprocess_ddradtags.pl with double digest sequences that have the DBR in the R2. When I run the script I get the following errors:

$ preprocess_ddradtags.pl -l ddRAD1_R1.fastq.gz -r ddRAD1_R2.fastq.gz -b ddRAD_4bp_barcodes.txt -i NNNNNNMMGGACG -gz y
Global symbol "@lfq" requires explicit package name (did you forget to declare "my @lfq"?) at preprocess_ddradtags.pl line 251.
Global symbol "@rfq" requires explicit package name (did you forget to declare "my @rfq"?) at preprocess_ddradtags.pl line 252.
Global symbol "@lfq" requires explicit package name (did you forget to declare "my @lfq"?) at preprocess_ddradtags.pl line 289.
Global symbol "@rfq" requires explicit package name (did you forget to declare "my @rfq"?) at preprocess_ddradtags.pl line 290.
Global symbol "@lfq" requires explicit package name (did you forget to declare "my @lfq"?) at preprocess_ddradtags.pl line 294.
Global symbol "@rfq" requires explicit package name (did you forget to declare "my @rfq"?) at preprocess_ddradtags.pl line 295.
Global symbol "@lfq" requires explicit package name (did you forget to declare "my @lfq"?) at preprocess_ddradtags.pl line 299.
Global symbol "@rfq" requires explicit package name (did you forget to declare "my @rfq"?) at preprocess_ddradtags.pl line 300.
Global symbol "@lfq" requires explicit package name (did you forget to declare "my @lfq"?) at preprocess_ddradtags.pl line 304.
Global symbol "@rfq" requires explicit package name (did you forget to declare "my @rfq"?) at preprocess_ddradtags.pl line 305.
Global symbol "@lfq" requires explicit package name (did you forget to declare "my @lfq"?) at preprocess_ddradtags.pl line 309.
Global symbol "@rfq" requires explicit package name (did you forget to declare "my @rfq"?) at preprocess_ddradtags.pl line 310.
Global symbol "@lfq" requires explicit package name (did you forget to declare "my @lfq"?) at preprocess_ddradtags.pl line 314.
Global symbol "@rfq" requires explicit package name (did you forget to declare "my @rfq"?) at preprocess_ddradtags.pl line 315.
Global symbol "@lfq" requires explicit package name (did you forget to declare "my @lfq"?) at preprocess_ddradtags.pl line 319.
Global symbol "@rfq" requires explicit package name (did you forget to declare "my @rfq"?) at preprocess_ddradtags.pl line 320.
Global symbol "$c_total" requires explicit package name (did you forget to declare "my $c_total"?) at preprocess_ddradtags.pl line 600.

Can you offer suggestions on how to fix this?

**Comment by alephreish** [comment]
Hi! Thanks for reporting the bug, I've fixed it in [the latest commit](https://github.com/evoeco/radtools/commit/2e675f8d5dd0940c5566984c1f4cb4f984def29c). Let me know if you face other problems.
